---
title: "Elemzes"
author: "Balint Mazzag"
date: '2021 10 25 '
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
NiceName <- function(x) {
  case_when(
    x == "tfr" ~ "Teljes termékenységi arányszám",
    x == "family_benefit" ~ "Állami családi juttatások mértéke",
    x == "net_migration" ~ "Nettó migráció (teljes lakosság arányában)",
    x == "NY.GDP.PCAP.CD" ~ "Egy főre jutó GDP",
    x == "SI.POV.GINI" ~ "Jövedelmi GINI index",
    x == "SE.SEC.ENRR.FE" ~ "Középszintű oktatásban résztvevő nők aránya",
    x == "SL.UEM.TOTL.FE.NE.ZS" ~ "Női munkanélküliségi ráta",
    x == "SL.UEM.TOTL.NE.ZS" ~ "Teljes munkanélküliségi ráta",
    x == "SP.DYN.LE00.FE.IN" ~ "Nők várható élettartama",
    x == "SP.DYN.LE00.IN" ~ "Várható élettartam",
    x == "adjTFR" ~ "Tempó-igazított termékenységi ráta",
    TRUE ~ x
  )
}


```


```{r setup, include=FALSE}
library(tidyverse)
library(WDI)

WD <- getwd() %>% 
  gsub(pattern = "kutatasmodszertan.*", replacement = "kutatasmodszertan")


setwd(WD)
```

```{r data_load}

pwt <- readxl::read_xlsx("data/pwt100.xlsx", sheet = "Data")

tfr <- read_csv("data/DP_LIVE_25102021172144615.csv") %>% 
  transmute(iso2c = countrycode::countrycode(LOCATION, origin = "iso3c", destination = "iso2c"), 
            year = TIME, 
            tfr = Value)

family_benefit <- read_csv("data/DP_LIVE_25102021174058939.csv") %>% 
  filter(SUBJECT == "TOT") %>% 
  transmute(iso2c = countrycode::countrycode(LOCATION, origin = "iso3c", destination = "iso2c"), 
            year = TIME, 
            family_benefit = Value)

gdp_per_capita <- WDI(indicator = "NY.GDP.PCAP.CD")
gini <- WDI(indicator = "SI.POV.GINI")
fem_education <- WDI(indicator = "SE.SEC.ENRR.FE")
fem_unemployment <- WDI(indicator = "SL.UEM.TOTL.FE.NE.ZS")
tot_unemployment <- WDI(indicator = "SL.UEM.TOTL.NE.ZS")
fem_life_expect <- WDI(indicator = "SP.DYN.LE00.FE.IN")
tot_life_expect <- WDI(indicator = "SP.DYN.LE00.IN")

net_migration <- readxl::read_xlsx("data/WPP2019_MIGR_F01_NET_MIGRATION_RATE.xlsx") %>% 
  filter(Type == "Country/Area") %>% 
  select(country = 3, 8:ncol(.)) %>% 
  pivot_longer(-1) %>% 
  transmute(iso2c = countrycode::countrycode(country, origin = "country.name", destination = "iso2c"),
            year = as.numeric(name),
            net_migration = as.numeric(value))



full_data <- list(gdp_per_capita, tfr, family_benefit, fem_education, fem_life_expect, fem_unemployment, tot_life_expect, tot_unemployment, gini, net_migration) %>% 
  reduce(left_join)

oecd_countries <- family_benefit %>% select(iso2c) %>% unique() %>% pull()

filtered_data <- full_data %>% 
  filter(iso2c %in% oecd_countries & iso2c != "NZ")


filtered_data %>% 
  group_by(country) %>%  
  summarize_all(funs(sum(!is.na(.)))) %>% 
  ungroup()
```


```{r}
safely_interpolate <- function(x) {
  if (sum(!is.na(x)) > 2) {
    approxfun(x)(seq_along(x))
  } else {
    x
  }
}

df_safely_imputed <- filtered_data %>% 
  relocate(iso2c, year) %>% 
  arrange(year) %>% 
  select(-country) %>% 
  mutate_if(is.numeric, ~ ifelse(is.finite(.), ., NA)) %>%
  group_by(iso2c) %>% 
  group_modify(~ mutate_all(.x, safely_interpolate)) %>% 
  group_modify(~ fill(.x, everything(), .direction = "down")) %>% 
  ungroup()

df_safely_imputed %>% 
  pivot_longer(-(1:2)) %>% 
  group_by(iso2c, name) %>% 
  summarise(na = sum(is.na(value)), n = n(), ratio = na/n)

variable_list <- names(df_safely_imputed %>% select(-(1:2)))

```




```{r}
library(aTSA)

df_ts <- df_safely_imputed %>% 
  pivot_longer(-(1:2)) %>% 
  filter(iso2c != "NZ" | name != "SI.POV.GINI") %>% 
  filter(!is.na(value)) %>% 
  arrange(name, year)

variable_list <- df_ts %>% select(name) %>% unique() %>% pull()
country_list <- df_ts %>% select(iso2c) %>% unique() %>% pull()


df_all <-expand.grid(country_list, variable_list) %>% mutate_all(as.character) %>% filter(Var1 != "NZ" | Var2 != "SI.POV.GINI")
```


```{r}
#Running ADF tests
df_ts_filter <- 
  df_ts %>% split(list(df_ts$name, df_ts$iso2c)) %>% 
  {lapply(., function(x) ts(x$value, start = min(x$year), end = max(x$year)))}

df_ts_tested <- bind_cols(df_all, lapply(df_ts_filter, function(x){x %>% PP.test()}) %>% 
                            {lapply(., function(x){list(param = x[["parameter"]][["Truncation lag parameter"]], p_value = x$p.value) %>% data.frame()})} %>% 
                            reduce(rbind))
```


```{r}
#Granger-test
df_granger <- filter(df_all, Var2 != "tfr")

granger_causality <- map2_df(df_granger$Var2, df_granger$Var1,
                             ~ tibble(country = .y, 
                                      name = .x, 
                                      pvalue = df_safely_imputed %>% 
                                        filter(iso2c == .y) %>% 
                                        select(year, .x, tfr) %>% 
                                        na.omit() %>% 
                                        transmute(x = ts(.[,.x], start = min(.$year), end = max(.$year)),
                                                  y = ts(tfr, start = min(.$year), end = max(.$year))) %>% 
                                        lmtest::grangertest(order = df_ts_tested %>% filter(Var1 == .y, Var2 == .x) %>% pull(param)) %>% 
                                        .[2,4]))


var_models <- map2(df_granger$Var1, df_granger$Var2,
                   ~tibble(country = .x, 
                                      name = .y, 
                           coefficients = df_safely_imputed %>% 
                              filter(iso2c == .x) %>% 
                              select(year, .y, tfr) %>% 
                              na.omit() %>%
                              transmute(x = ts(.[,.y], start = min(.$year), end = max(.$year)),
                                        y = ts(tfr, start = min(.$year), end = max(.$year))) %>% 
                              vars::VAR(., p = df_ts_tested %>% filter(Var1 == .x, Var2 == .y) %>% pull(param), type = "const") %>% 
                     {.[["varresult"]][["y"]][["coefficients"]]})) %>% 
  {lapply(., function(z) cbind(z[,1:2], z %>% stack(coefficients)) %>% rownames_to_column("coefficients_name"))} %>% 
  reduce(rbind)

final_df <- left_join(var_models, granger_causality) %>% 
  pivot_wider(names_from = coefficients_name, values_from = values) %>% 
  select(country, name, pvalue, contains("x."))



```

```{r}

adjTFR <- readxl::read_excel("data/adjTFR.xlsx", 
                             sheet = "Tempo-adjusted TFR") %>% 
  {set_names(.[-c(1, 2), ], .[2, ])} %>% 
  pivot_longer(-1, names_to = "country", values_to = "adjTFR") %>% 
  rename(time = PERIOD) %>% 
  filter(adjTFR != 0 & !(country %in% c("DEUTE",	"DEUTW", "GBRTENW",	"GBR_NIR",	"GBR_SCO"))) %>% 
  transmute(
         iso2c = countrycode::countrycode(country, origin = "iso3c", destination = "iso2c"),
         year = as.double(time),
    adjTFR = as.numeric(adjTFR))

tfr_comp <- left_join(tfr, adjTFR)

tfr_comp %>% 
  pivot_longer(-(1:2)) %>% 
  filter(iso2c == "HU") %>% 
  ggplot(aes(x = year, y = value, color = NiceName(name)))+
  geom_line(size = 1.5) +
  geom_hline(yintercept = 2.1, linetype = "dashed", size = 1) + 
  scale_x_continuous(breaks = seq(1960, 2020, 5)) +
  scale_colour_brewer(palette = "Set2") +
  theme(legend.position = "bottom") +
  labs(y = "Termékenységi ráta",
       x = "Év",
       title = "Magyarország termékenységi rátájának alakulása",
       color = "Változó")
```

Legkorábbi adatpont elérhetősége

```{r}

df_safely_imputed %>% 
  pivot_longer(-(1:2)) %>% 
  filter(!is.na(value)) %>% 
  group_by(iso2c, name) %>% 
  slice_min(1) %>% 
  ungroup() %>% 
  select(-value) %>% 
  mutate(name = NiceName(name),
         iso2c = countrycode::countrycode(iso2c, origin = "iso2c", destination = "country.name")) %>% 
  pivot_wider(names_from = "name", values_from = "year") %>% 
  clipr::write_clip()

```


Francia adatok bemutatása

```{r}

df_safely_imputed %>% 
  filter(iso2c == "HU") %>% 
  pivot_longer(-(1:2)) %>% 
  ggplot(aes(x=year, y = value, color = NiceName(name))) +
  geom_line(size = 1.5) +
  scale_color_brewer(palette = "Set2") +
 facet_wrap(~NiceName(name), scales = "free")

df_safely_imputed %>% 
  select(iso2c, year, family_benefit) %>% 
  filter(iso2c %in% c("HU", "DE", "UK", "US", "FR", "SE", "CZ", "PL", "PT") & !is.na(family_benefit) & year <2018) %>% 
  ggplot(aes(x = year, y = family_benefit, group = iso2c, color = countrycode::countrycode(iso2c, origin = "iso2c", destination = "country.name"))) +
  geom_line(size = 1.5) +
  scale_colour_brewer(palette = "Set2") +
  labs(color = "Ország",
       x = "Év",
       y = "Állami családi juttatások mértéke")
  

df_safely_imputed %>% 
  filter(year == 2019 & net_migration > -5 & net_migration <5 ) %>% 
  ggplot(aes(x = `SL.UEM.TOTL.FE.NE.ZS`, y = `SI.POV.GINI`)) +
  geom_point() +
  ggrepel::geom_label_repel(aes(label = countrycode::countrycode(iso2c, origin = "iso2c", destination = "country.name"), fill = net_migration)) +
  scale_fill_gradient2(low = RColorBrewer::brewer.pal(3, "Set2")[2], high = RColorBrewer::brewer.pal(3, "Set2")[1]) +
  labs(x = "Női munkanélküliségi ráta",
       y = "Jövedelmi GINI index",
       fill = NiceName("net_migration"),
       title = "Országok 2019-as adatainak bemutatása") +
  theme(legend.position = "bottom")
```

Külön átlagok a három különböző csoportra

```{r}
df_safely_imputed %>%
  filter(year == 2020) %>% 
  pivot_longer(-(1:2)) %>% 
  mutate(name = NiceName(name)) %>% 
  pivot_wider(names_from = name, values_from = value) %>% 
  mutate(tfr_level = cut_number(`Teljes termékenységi arányszám`, 4, labels = c("low", "mid_low", "mid_high", "high"))) %>% 
  select(-iso2c) %>% 
  group_by(tfr_level) %>% 
  summarise(across(everything(), list(mean))) %>% 
  ungroup()
  #clipr::write_clip()

```

